openapi: 3.0.0
info:
  title: Posts API
  description: API for managing blog posts
  version: "1.0"
servers:
  - url: 'http://localhost:5000'
    description: Local server
paths:
  /posts/{id}:
    get:
      summary: Retrieves a single post
      description: Returns a single blog post by its ID.
      operationId: getPost
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier of the blog post
          schema:
            type: string
      responses:
        '200':
          description: A single post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Post:
        type: object
        properties:
          _id:
            type: string
            description: The auto-generated ID of the post.
          title:
            type: string
            description: The title of the post.
          message:
            type: string
            description: The content of the post.
          creator:
            type: string
            description: The creator's username of the post.
          tags:
            type: array
            items:
              type: string
            description: Tags associated with the post.
          selectedFile:
            type: string
            description: Base64 encoded image data of the post.
          likeCount:
            type: integer
            default: 0
            description: The count of likes the post has received.
          createdAt:
            type: string
            format: date-time
            description: The date and time when the post was created.
        required:
          - title
          - message
          - creator
          - tags
          - selectedFile
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
