openapi: 3.0.0
info:
  title: Posts API
  description: API for managing blog posts
  version: "1.0"
servers:
  - url: 'http://localhost:5000'
    description: Local server
paths:
  /posts:
    get:
      summary: Retrieves all posts
      description: Returns an array of all the blog posts in the database.
      operationId: getPosts
      responses:
        '200':
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '404':
          description: Unable to retrieve posts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Post:
      type: object
      required:
        - title
        - message
        - creator
        - tags
        - selectedFile
        - likeCount
        - createdAt
      properties:
        title:
          type: string
        message:
          type: string
        creator:
          type: string
        tags:
          type: array
          items:
            type: string
        selectedFile:
          type: string
        likeCount:
          type: integer
          default: 0
        createdAt:
          type: string
          format: date-time
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
