openapi: 3.0.0
info:
  title: Update Post API
  description: API for updating blog posts
  version: "1.0.0"
servers:
  - url: http://localhost:5000
paths:
  /posts/{id}:
    patch:
      summary: Update a post
      operationId: updatePost
      tags:
        - posts
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier of the post to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
            example:
              title: "Updated Title"
              message: "Updated content of the post."
              creator: "User1"
              tags: ["updated", "post"]
              selectedFile: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA..."
      responses:
        '200':
          description: Successfully updated post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post not found
        '400':
          description: Invalid input, object invalid

components:
  schemas:
    Post:
      type: object
      properties:
        _id:
          type: string
          description: The auto-generated ID of the post.
        title:
          type: string
          description: The title of the post.
        message:
          type: string
          description: The content of the post.
        creator:
          type: string
          description: The creator's username of the post.
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the post.
        selectedFile:
          type: string
          description: Base64 encoded image data of the post.
        likeCount:
          type: integer
          default: 0
          description: The count of likes the post has received.
        createdAt:
          type: string
          format: date-time
          description: The date and time when the post was created.
      required:
        - title
        - message
        - creator
        - tags
        - selectedFile
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
